### ISSUE TITLE
Missing request header "origin"

### ISSUE THREAD

**Issue by akiross** [Bassetts/warp-cors#15]
Hello,
I just tried warp-cors from a container, using an example as advertised, but requests fail.

Here's how I ran it: `podman run -it --rm -p3030:3030 bassetts/warp-cors`

Going to http://localhost:3030/https://example.org or https://localhost:3030/https://example.org i see the message

```
Missing request header "origin"
```

Am I missing something?
Thanks

**Comment by Bassetts** [comment]
Hi,

Thanks for using my project! 

When you go to those example URLs is that from a browser or are you using something like Postman? The reason I ask is an `Origin` header is required in the request sent to warp-cors as it uses this to set the `Access-Control-Allow-Origin` on the proxied response.

I could have just set `Access-Control-Allow-Origin: *` but made a conscious decision to only set the header for the origin in the original request.

Using warp-cors from anything but a browser doesn't really make sense as CORS is only really an issue in that environment, and the browser should be providing an `Origin` header.

Hope that helps

**Comment by Bassetts** [comment]
I have done some further testing on this and it seems browsers are not always sending the `Origin` header. I am working on a change that will use the value from the `Origin` header for the `Access-Control-Allow-Origin` header in the proxied response if it is present, otherwise `Access-Control-Allow-Origin: *` will be used.

**Comment by Bassetts** [comment]
The new version has now been released. If you update your container to use `0.3.0` then the issue you were seeing should be resolved. Please let me know if you have any other issues. Thanks again for using my project 👍

**Comment by akiross** [comment]
Hello @Bassetts, sorry for the late reply: yep I was indeed using a browser (firefox).

Thanks for your investigation and updates, very appreciated! Now it works as expected using both http and https.
